apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apparmorprofiles.apparmor.security.kubernetes.io
  labels:
    app.kubernetes.io/name: apparmor-operator
    app.kubernetes.io/version: "1.0.0"
spec:
  group: apparmor.security.kubernetes.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              profileName:
                type: string
                description: "Name of the AppArmor profile"
                pattern: "^[a-zA-Z0-9._-]+$"
                maxLength: 64
              profileContent:
                type: string
                description: "The actual AppArmor profile rules"
                minLength: 1
              enforcementMode:
                type: string
                description: "How the profile should be enforced"
                enum: ["enforce", "complain", "audit"]
                default: "enforce"
              networkRules:
                type: array
                description: "Network microsegmentation rules"
                items:
                  type: object
                  properties:
                    protocol:
                      type: string
                      enum: ["tcp", "udp", "icmp", "raw"]
                    port:
                      type: integer
                      minimum: 1
                      maximum: 65535
                    address:
                      type: string
                      description: "CIDR notation for network address"
                      pattern: "^([0-9]{1,3}\\.){3}[0-9]{1,3}(/[0-9]{1,2})?$"
                    action:
                      type: string
                      enum: ["allow", "deny", "audit"]
                  required: ["protocol", "action"]
              conditionalRules:
                type: array
                description: "Conditional policy rules"
                items:
                  type: object
                  properties:
                    condition:
                      type: string
                      description: "Expression for evaluation"
                      minLength: 1
                    action:
                      type: string
                      enum: ["allow", "deny", "audit"]
                    priority:
                      type: integer
                      minimum: 1
                      maximum: 1000
                      default: 100
                  required: ["condition", "action"]
              autoGenerated:
                type: boolean
                description: "Indicates if this profile was auto-generated"
                default: false
              aiOptimized:
                type: boolean
                description: "Indicates if this profile was optimized by AI/ML"
                default: false
              version:
                type: string
                description: "Version tracking for profile evolution"
                pattern: "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$"
                default: "1.0"
            required: ["profileName", "profileContent"]
          status:
            type: object
            properties:
              phase:
                type: string
                description: "Current phase of the profile"
                enum: ["Pending", "Active", "Error", "Terminating"]
              message:
                type: string
                description: "Additional information about the status"
              lastUpdated:
                type: string
                format: date-time
                description: "When the profile was last updated"
              appliedToPods:
                type: array
                description: "List of pods using this profile"
                items:
                  type: string
              violations:
                type: array
                description: "Security violations"
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                      format: date-time
                    podName:
                      type: string
                    violation:
                      type: string
                    severity:
                      type: string
                      enum: ["low", "medium", "high", "critical"]
                  required: ["timestamp", "podName", "violation", "severity"]
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
        labelSelectorPath: .status.selector
  scope: Namespaced
  names:
    plural: apparmorprofiles
    singular: apparmorprofile
    kind: AppArmorProfile
    shortNames:
    - aap
    - apparmor
    categories:
    - security
    - apparmor
